### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by JonesWest** [stevenpack/phonegap-multicastdns#1]
Hi Steven, 

I don't know if this is the right place for this question, but I hope you can just delete it if it isn't. 

I am quite new to the ionic framework (based on ngCordova and AngularJS), and I really need mDNS support for android, but I can't figure out how to use your library in AngularJS?

Also I've made a question on StackOverflow as well: http://stackoverflow.com/questions/35032478/how-to-use-custom-cordova-plugin-in-angularjs-ionic

Thanks in advance.

**Comment by stevenpack** [comment]
Yo - replied on SO.
